name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node App to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Clean up old app if it exists
          rm -rf /home/deploy/node-app

          # Make a fresh folder
          mkdir -p /home/deploy/node-app
          cd /home/deploy/node-app

          # Initialize git
          git init

          # Clone fresh
          git clone https://github.com/Jereck/terraform-nodejs-ect.git

          # Enable sparse checkout
          git sparse-checkout init --cone
          git sparse-checkout set node-app

          # Pull only the node-app folder
          git pull origin main

          # Move into node-app folder
          cd node-app

          # Install dependencies
          npm install

          # Start or restart app with PM2
          pm2 delete node-server || true
          pm2 start server.js --name node-server
          pm2 save
